app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('brands.urls')),
    path('', include('categories.urls')),
    path('', include('suppliers.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('products.urls')),
]

outflows/urls.py
from django.urls import path
from .views import OutflowListView, OutflowCreateView, OutflowDetailView

urlpatterns = [
    path('outflows/list/', OutflowListView.as_view(), name="outflow_list"),
    path('outflows/create/', OutflowCreateView.as_view(), name='outflow_create'),
    path('outflows/<int:pk>/detail/', OutflowDetailView.as_view(), name="outflow_detail"),
 
]

inflows/models.py
from django.db import models
from products.models import Product
from suppliers.models import Supplier


class Inflow(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, related_name="inflows")
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='inflows')
    quantity = models.IntegerField()
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
        
    def __str__(self):
        return str(self.product)

    

outflows/models.py
from django.db import models
from products.models import Product


class Outflow(models.Model):    
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='outflows')
    quantity = models.IntegerField()
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
        
    def __str__(self):
        return str(self.product)

outflows/forms.py
from django import forms
from . models import Outflow
from django.core.exceptions import ValidationError


class OutflowModelForm(forms.ModelForm):
    class Meta:
        model = Outflow
        fields = ['product', 'quantity', 'description']
        
        widgets = {
            
            'product': forms.Select(attrs={'class':'form-control'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3})
        }
        
        labels = {
            
            'product': 'Produto',
            'quantity': 'Quantidade',
            'description': 'Descrição'
        }
        
    def clean_quantity(self):
            quantity = self.cleaned_data.get('quantity')
            product = self.cleaned_data.get('product')         
            
            if quantity > product.quantity:
                raise ValidationError(
                    f'A quantidade disponivel em estoque para o produto {product.title} é de {product.quantity} unidades.'
                )
                
            return quantity
               

outflows/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Outflow
from .forms import OutflowModelForm


class OutflowListView(ListView):
    model = Outflow
    template_name = 'outflow_list.html'
    context_object_name = 'outflows'
    paginate_by = 10
    
    def get_queryset(self):
        queryset = super().get_queryset()
        product = self.request.GET.get('product')
        
        if product:
            queryset = queryset.filter(product__title__icontains=product)
            
        return queryset
    
    
class OutflowCreateView(CreateView):
    model = Outflow
    template_name = 'outflow_create.html'
    form_class =  OutflowModelForm
    success_url = reverse_lazy('outflow_list')
    
class OutflowDetailView(DetailView):
    model = Outflow
    template_name = 'outflow_detail.html'

outflows/templates/outflow_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h3 class="display-6">Cadastrar Saida</h3>
    <div class="card">
        <div class="card-body">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Registrar Saida</button>
            </form>

        </div>
    </div>
    <a href="{% url 'inflow_list' %}" class="btn btn-secondary mt-3 ">Cancelar e voltar para a lista</a>
</div>

{% endblock %}

outflows/templates/outflow_detail.html
{% extends 'base.html' %}

{% block title %}Entrada detalhes{% endblock %}
{% block content %}

<div class="container mt-4">
    <h1 class="display-6">Detalhes da Saida</h1>
    <div class="card">
        <div class="card-body">
             <h3 class="card-title">{{ object.product }}</h3>           
             <p class="card-text">Quantidade: <strong>{{ object.quantity }}</strong></p>
             <p class="card-text">{{ object.description }}</p>
        </div>
    </div>
    <a href="{% url 'outflow_list' %}" class="btn btn-secondary mt-3 ">Voltar para a lista</a>    
</div>
{% endblock%}

outflows/templates/outflow_list.html
{% extends 'base.html'%}

{% block title %}Categorias{% endblock %}

{% block content %}

<div class="row mb-3">
    <div class="col-md-6">
        <form action="{% url 'outflow_list' %}" method="get">
            <div class="input-group">
                <input type="text" class="form-control" name="product" placeholder="Product" value="{{ request.GET.product}}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <a href="{% url 'outflow_create' %}" class="btn btn-success float-end" >
            <i class="bi bi-plus"></i> Registrar Saida
        </a>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Produto</th>      
                <th>Quantidade</th>
                <th>Data Saida</th>
                <th>Açôes</th>

            </tr>
        </thead>
        <tbody>
            {% for outflow in outflows %}
            <tr>
                <th>{{ outflow.id }}</th>               
                <th>{{ outflow.product }}</th>
                <th>{{ outflow.quantity }}</th>
                <th>{{ outflow.created_at }}</th>
                <th>
                    <a href="{% url 'outflow_detail' outflow.id %}" class="btn btn-info btn-sm">
                        <i class="bi bi-eye"></i>
                    </a>                   
                </th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% include 'components/_pagination.html' %}

{% endblock %}