app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('brands.urls')),
    path('', include('categories.urls')),
    path('', include('suppliers.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('products.urls')),
]

categories/urls.py
from django.urls import path
from . views import CategoryListView, CategoryCreateView, CategoryDetailView, CategoryUpdateView,  CategoryDeleteView         


urlpatterns = [
    path('categories/list/', CategoryListView.as_view(), name='category_list'),
    path('categories/create/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/detail/', CategoryDetailView.as_view(), name='category_detail'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete')
    
]

brands/models.py
from django.db import models


class Brand(models.Model):
    name =  models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['name']
        
    def __str__(self):
        return self.name

categories/models.py
from django.db import models


class Category(models.Model):
    name =  models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['name']
        
    def __str__(self):
        return self.name

categories/forms.py
from django import forms
from .models import Category


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3})
        }
        labels = {
            'name': 'Nome',
            'description': 'Descrição'
        }

categories/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from . models import Category
from . forms import CategoryModelForm


class CategoryListView(ListView):
    model = Category
    template_name = 'category_list.html'
    context_object_name = 'categories'
    paginate_by = 10
    
    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get('name')
        
        if name:
            queryset = queryset.filter(name__icontains=name)
            
        return queryset
    
class CategoryCreateView(CreateView):
    model = Category
    template_name = 'category_create.html'
    form_class =  CategoryModelForm
    success_url =  reverse_lazy('category_list')
    
class CategoryDetailView(DetailView):
    model = Category
    template_name = 'category_detail.html'
    
class CategoryUpdateView(UpdateView):
    model = Category
    template_name =  'category_update.html'
    form_class = CategoryModelForm
    success_url = reverse_lazy('category_list')

class CategoryDeleteView(DeleteView):
    model = Category
    template_name = 'category_delete.html'
    success_url = reverse_lazy('category_list')
      
    

categories/templates/category_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h3 class="display-6">Cadastrar Categoria</h3>
    <div class="card">
        <div class="card-body">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>

        </div>
    </div>
    <a href="{% url 'brand_list' %}" class="btn btn-secondary mt-3 ">Cancelar e voltar para a lista</a>
</div>

{% endblock %}

categories/templates/category_delete.html
{% extends 'base.html' %}

{% block title %}Marca detalhes{% endblock %}
{% block content %}

<div class="container mt-4">
    <h1 class="display-6">Deletar da Marca</h1>
    <div class="card">
        <div class="card-body">
             
             <p class="card-text">tem certeza que deseja excluir a categoria <strong>{{ object.name }} ?</strong></p>
             <form action="" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-secondary btn-sm">Deletar</button>
             </form>
        </div>
    </div>
    <a href="{% url 'brand_list' %}" class="btn btn-secondary mt-3 ">Voltar para a lista</a>    
</div>
{% endblock%}

categories/templates/category_detail.html
{% extends 'base.html' %}

{% block title %}Categoria detalhes{% endblock %}
{% block content %}

<div class="container mt-4">
    <h1 class="display-6">Detalhes da Categoria</h1>
    <div class="card">
        <div class="card-body">
             <h3 class="card-title">{{ object.name }}</h3>
             <p class="card-text">{{ object.description }}</p>
        </div>
    </div>
    <a href="{% url 'brand_list' %}" class="btn btn-secondary mt-3 ">Voltar para a lista</a>    
</div>
{% endblock%}

categories/templates/category_list.html
{% extends 'base.html'%}

{% block title %}Categorias{% endblock %}

{% block content %}

<div class="row mb-3">
    <div class="col-md-6">
        <form action="{% url 'category_list' %}" method="get">
            <div class="input-group">
                <input type="text" class="form-control" name="name" placeholder="Nome" value="{{ request.GET.name}}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <a href="{% url 'category_create' %}" class="btn btn-success float-end" >
            <i class="bi bi-plus"></i> Nova Categoria
        </a>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Açôes</th>

            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
            <tr>
                <th>{{ category.id }}</th>
                <th>{{ category.name }}</th>
                <th>{{ category.description }}</th>
                <th>
                    <a href="{% url 'category_detail' category.id %}" class="btn btn-info btn-sm">
                        <i class="bi bi-eye"></i>
                    </a>
                    <a href="{% url 'category_update' category.id %}" class="btn btn-warning btn-sm">
                        <i class="bi bi-pencil"></i>
                    </a>
                    <a href="{% url 'category_delete' category.id %}" class="btn btn-danger btn-sm">
                        <i class="bi bi-trash"></i>
                    </a>
                </th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% include 'components/_pagination.html' %}

{% endblock %}

categories/templates/category_update.html
{% extends 'base.html' %}

{% block title %}Marca Atualização{% endblock %}
{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Atualizar Categoria</h3>
    <div class="card">
        <div class="card-body">
            <form action="" method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>

        </div>
    </div>
    <a href="{% url 'brand_list' %}" class="btn btn-secondary mt-3 ">Cancelar e voltar para a lista</a>
</div>
{% endblock%}